### ISSUE TITLE
Typos and code snippet

### ISSUE THREAD

**Issue by ryanroderick1** [nikhilnayak98/CSE2041#2]
Hey,

Thank you for putting this beautiful code online.  I’m learning a lot from it.

I just wanted to let you know that there are two typos in your answer for the Chapter6, ProgrammingProjects, PositiveIntegers problem.

The first typo is in the main function call statement for 

check(num, &q1, &q1, &q3). 

Obviously, it should read 

check(num, &q1, &q2, &q3). 

The second typo is in the it statements in the main function as well.  There are two

if(q2 == 1) statements.

Obviously the third one should read

if(q3 == 1) .

Finally, the sub function 

int digits_odd(int num) 

seems to tell us whether the number of digits in the given number is even or odd.  But the question asks if the SUM of those digits is even or odd.

I solved the problem with this code snippet:

if(num == 0)
    total = 0;
else
{
    while(num != 0)
    {
    temp = num % 10;
    total += temp;
    num / = 10;
    }
}
if(total % 2 != 0)
    return 1;
return 0;

I would love to do a pull request to help solve these kinds of issues, as I am working through the book in order to learn C.  Please let me know if this is OK, as I am new to GitHub.

Best, 

Ryan

**Comment by nikhilnayak98** [comment]
Sure thing! Create a pull request.

**Comment by nikhilnayak98** [comment]
#3
