### ISSUE TITLE
Re-set “sum _of _point”, ch 7 PointMass

### ISSUE THREAD

**Issue by ryanroderick1** [nikhilnayak98/CSE2041#5]
Hey Nikhil,

I really appreciate all of the code you left in this repository.

In the programming projects for chapter 7, I learned from your code for "PointMass" that I needed to add up the sum of the points to get the correct formula for the solution.

After I desk checked the answer and completed my program, I compared it to yours, and I noticed that your answer was different than mine.  After some "printf" debugging, I noticed that your program does not reset the "sum_of_point" variable after it adds up each set of points.

I added the assignment statement, "sum_of_point = 0;" at line 57, and that fixed the logic error.

I would like to initiate a pull request to add the needed line of code to your program.  Is that OK?

Please let me know.

Ryan

**Comment by nikhilnayak98** [comment]
Sure go ahead!

**Comment by ryanroderick1** [comment]
Hey Nikhil, 

I was wondering if you could show me how you set up your GitHub with those files.  I would be happy to pay you as a tutor over PayPal or another payment app.  We could work on Microsoft teams or zoom, etc., for screen sharing.  I can pay you $40 per hour.  Please let me know if you are interested.

Ryan
